`timescale 1ns/1ps
// -----------------------------------------------------------------------------
// fw_uart_tb.sv — a firmware kernel through the whole core, over the UART only.
//
// The successor to the retired tpu_top_uart_tb.sv (which drove the scalar unit's
// assembled `.tpu` programs the same way) and the serial counterpart of
// fw_matmul_tb.sv. Where that test backdoors the image in through cpu_subsys's
// FW_INIT `$readmemh` and pokes DRAM straight into the chip model, this one
// touches nothing but the two serial pins:
//
//   1. 'I'  load ../fw/<kernel>.hex into the PicoRV32's firmware RAM
//   2. 'W'  write the operand image — weights included — into external DRAM
//   3. 'G'  release the core at FW_BASE
//   4.      the firmware pushes its macro-ops; the units compute
//   5. 'T'  read the performance counters back
//   6. 'R'  read the result bytes back out of DRAM and compare
//
// That is exactly the sequence host/run_fw_matmul.py runs on the board, so a
// pass here says the board path is wired end to end and not only that the
// datapath computes. `host_run`, `imem_*` and `cfg_*` are tied off; the only
// backdoor is the behavioural SRAM chip model hanging off the DRAM pins, and it
// is read (never written) for the stray-write sweep at the end.
//
// Golden data is the ISS's, via ../../tpulang/fw_vectors.py — the same three
// files fw_matmul_tb.sv consumes, regenerated by the Makefile from the kernel's
// own native command trace before every run:
//
//   vectors_fw/fw_dram_in.hex    operands to write over 'W'
//   vectors_fw/fw_dram_exp.hex   every DRAM byte the run should have written
//   vectors_fw/fw_cmds.hex       the command stream the firmware should produce
//
// Four things are therefore checked:
//
//   1. the result bytes read back over 'R'   — the end-to-end serial path
//   2. every other byte of DRAM (backdoor)   — no stray writes anywhere
//   3. the command trace                     — did the CPU issue what the ISS ran
//   4. the counter block from 'T'            — self-consistent, and the run
//                                              length agrees with `busy`
//
// (2) is the one check that cannot go over the wire: reading 512 KB back at
// 10*UART_CPB clocks a byte would cost more simulation than every kernel here
// put together. It is a backdoor peek at the same memory the UART just wrote,
// so it does not weaken (1) — it extends it to the addresses (1) cannot afford.
//
//   make fwuart FWPROG=ffn          ~12 s
//   make fwuart FWPROG=adder        the whole model, weights and all
//   make fwuart FWPROG=ffn RERUN=1  load and run a second time, no reset
//
// The kernel is shape-agnostic: it replays whatever image fw_vectors.py wrote,
// so `make fwuart FWPROG=matmul M=8 KTILES=16 NTILES=16` needs no -D here.
//
// UART_CPB is the clocks-per-bit the DUT's serial blocks are built with. 16 is
// fast enough to simulate and slow enough to keep the receiver's mid-bit sample
// clear of the two-flop synchroniser (it lands at CPB/2 + 2 of CPB); the board
// builds 104. Lowering it below 8 is not safe for that reason.
// -----------------------------------------------------------------------------

`ifndef FW_HEX
  `define FW_HEX "../fw/matmul.hex"
`endif
`ifndef FW_NAME
  `define FW_NAME "matmul"
`endif
`ifndef FW_VEC_DIR
  `define FW_VEC_DIR "vectors_fw"
`endif
`ifndef UART_CPB
  `define UART_CPB 16
`endif
// Watchdogs. Not one absolute deadline: the run and the link fail in different
// ways and a bound loose enough for the adder's 454 k compute clocks would be
// useless against a wedged link. See the two processes at the bottom.
`ifndef RUN_MAX_NS
  `define RUN_MAX_NS 100000000
`endif
`ifndef LINK_IDLE_NS
  `define LINK_IDLE_NS 2000000
`endif
// Bytes per 'W'/'I'/'R' frame. The protocol's length field is 16 bits, and the
// adder's weight block is one 98 304-byte contiguous run, so chunking is
// required, not a tuning knob.
`ifndef UART_CHUNK
  `define UART_CHUNK 4096
`endif

module fw_uart_tb;

    // ---- geometry (must match the DUT the firmware was built for) ----------
    localparam int ROWS       = 8;
    localparam int COLS       = 8;
    localparam int ADDR_W     = 16;
    localparam int XLEN       = 32;
    localparam int M0_W       = 12;
    localparam int N_W        = 4;
    localparam int IMEM_AW    = 10;
    localparam int CFG_AW     = 5;
    localparam int FW_AW      = 12;
    localparam int MEM_ADDR_W = 19;
    localparam int MEM_DATA_W = 8;

    localparam int CLK_NS = 10;
    localparam int CPB    = `UART_CPB;

    // 'I'/'G' word addresses carry this in the top bit to name the CPU's
    // firmware RAM (host/tpu_uart.py FW_BASE). tpu_top no longer decodes it —
    // the scalar unit it used to select is gone — but the host still sends it,
    // so the testbench does too.
    localparam int FW_BASE = 1 << FW_AW;

    localparam [7:0] WCMD = 8'h57, RCMD = 8'h52, ICMD = 8'h49, GCMD = 8'h47,
                     TCMD = 8'h54;
    localparam [7:0] ACK  = 8'h06, NAK  = 8'h15;

    // Counter block returned by 'T'. Mirrors tpu_top.sv's NPERF / PERF_*.
    localparam int NPERF = 10;
    localparam int P_RUN = 0, P_MXU = 1, P_MLOAD = 2, P_VPU = 3, P_DMA = 4,
                   P_SWAIT = 5, P_VMM = 6, P_IDLEC = 7, P_QFULL = 8, P_OVLAP = 9;

    // Word w of a 'T' reply. uart_read_timer() shifts bytes in from the low end,
    // so the first word received (counter 0) ends up in the highest slice.
    function automatic logic [31:0] ctr_w(input logic [NPERF*32-1:0] ctr,
                                          input int w);
        return ctr[(NPERF-1-w)*32 +: 32];
    endfunction

    localparam int SRAM_SZ = 1 << MEM_ADDR_W;
    localparam int FW_DEPTH = 1 << FW_AW;
    localparam int MAX_CMDS = 8192;   // `infer` is 4606 (fw_matmul_tb.sv)

    int errors = 0, checks = 0;
    int unsigned cyc = 0;

    logic clk = 0, rst_n = 0;
    always #(CLK_NS/2) clk = ~clk;
    always @(posedge clk) cyc++;

    // ---- DUT ----------------------------------------------------------------
    logic               busy, done;
    logic [IMEM_AW-1:0] pc_dbg;

    wire  [MEM_ADDR_W-1:0] sram_addr;
    wire  [MEM_DATA_W-1:0] sram_data;
    wire                   sram_we, sram_ce, sram_oen;

    logic uart_rx = 1'b1;   // host -> device, idles high
    wire  uart_tx;          // device -> host

    // FW_INIT is deliberately empty: the image has to arrive over the wire, so a
    // stale ../fw/*.hex left behind by another target cannot be what runs.
    tpu_top #(
        .ROWS(ROWS), .COLS(COLS), .ADDR_W(ADDR_W),
        .XLEN(XLEN), .M0_W(M0_W), .N_W(N_W), .IMEM_AW(IMEM_AW), .CFG_AW(CFG_AW),
        .FW_AW(FW_AW), .FW_INIT(""),
        .MEM_STYLE("BRAM"), .MEM_ADDR_W(MEM_ADDR_W), .MEM_DATA_W(MEM_DATA_W),
        .UART_CPB(CPB), .UART_RX_TIMEOUT(0)
    ) dut (
        .clk(clk), .rst_n(rst_n),
        .host_run(1'b0), .boot_pc('0),
        .busy(busy), .done(done), .pc_dbg(pc_dbg),
        .imem_we(1'b0), .imem_waddr('0), .imem_wdata('0),
        .cfg_we(1'b0), .cfg_waddr('0), .cfg_wdata('0),
        .sram_addr(sram_addr), .sram_data(sram_data),
        .sram_we(sram_we), .sram_ce(sram_ce), .sram_oen(sram_oen),
        .uart_rx(uart_rx), .uart_tx(uart_tx)
    );

    // ---- behavioural async SRAM chip (same model as fw_matmul_tb) -----------
    logic [MEM_DATA_W-1:0] sram_mem [0:SRAM_SZ-1];

    wire mem_drives = (sram_ce == 1'b0) && (sram_oen == 1'b0) && (sram_we == 1'b1);
    assign #3 sram_data = mem_drives ? sram_mem[sram_addr] : {MEM_DATA_W{1'bz}};
    always @(posedge sram_we) if (sram_ce == 1'b0) sram_mem[sram_addr] <= sram_data;

    // ---- vector / image backing stores --------------------------------------
    logic [31:0] fw_words [0:FW_DEPTH-1];
    logic [7:0]  dram_in  [0:SRAM_SZ-1];
    logic [7:0]  dram_exp [0:SRAM_SZ-1];
    logic [31:0] cmd_exp  [0:MAX_CMDS*5-1];
    int          n_cmd_exp, n_fw_words;

    function automatic logic defined8 (input logic [7:0]  b); return (^b  !== 1'bx); endfunction
    function automatic logic defined32(input logic [31:0] w); return (^w  !== 1'bx); endfunction

    // ---- command-trace monitor ----------------------------------------------
    // Same probe as fw_matmul_tb: tpu_top's arbitrated command write, which is
    // where the CPU's dispatches converge on the queues.
    int          n_cmd_got = 0;
    int unsigned cmd_got [0:MAX_CMDS*5-1];

    always @(posedge clk) begin
        if (rst_n && dut.p_cmd_we && !dut.p_cmd_full) begin
            if (n_cmd_got < MAX_CMDS) begin
                cmd_got[n_cmd_got*5 + 0] = dut.p_cmd_unit;
                cmd_got[n_cmd_got*5 + 1] = dut.p_cmd_data[31:0];
                cmd_got[n_cmd_got*5 + 2] = dut.p_cmd_data[63:32];
                cmd_got[n_cmd_got*5 + 3] = dut.p_cmd_data[95:64];
                cmd_got[n_cmd_got*5 + 4] = dut.p_cmd_data[127:96];
            end
            n_cmd_got++;
        end
    end

    // ---- independent measure of the run length ------------------------------
    // What the 'T' reply's word 0 should say, derived from the `busy` pin rather
    // than from any counter inside the DUT.
    time t_busy_rise, t_busy_fall;
    always @(posedge busy) t_busy_rise = $time;
    always @(negedge busy) t_busy_fall = $time;

    function automatic int unsigned busy_clocks();
        return int'((t_busy_fall - t_busy_rise) / CLK_NS);
    endfunction

    // Last time either serial line moved — the link watchdog's input.
    time last_wire_edge = 0;
    always @(uart_rx or uart_tx) last_wire_edge = $time;

    // =========================================================================
    // UART host: bit-bang uart_rx, decode uart_tx.
    // =========================================================================
    task automatic tx_byte(input [7:0] b);
        uart_rx = 1'b0;                         // start bit
        repeat (CPB) @(posedge clk);
        for (int i = 0; i < 8; i++) begin
            uart_rx = b[i];                     // LSB first
            repeat (CPB) @(posedge clk);
        end
        uart_rx = 1'b1;                         // stop bit
        repeat (CPB) @(posedge clk);
    endtask

    task automatic rx_byte(output [7:0] b);
        @(negedge uart_tx);                     // start bit
        repeat (CPB / 2) @(posedge clk);        // to the middle of it
        for (int i = 0; i < 8; i++) begin
            repeat (CPB) @(posedge clk);
            b[i] = uart_tx;
        end
        repeat (CPB) @(posedge clk);            // stop bit
    endtask

    // CMD + 24-bit addr (BE) + 16-bit len (BE)
    task automatic send_header(input [7:0] cmd, input [23:0] a, input [15:0] n);
        tx_byte(cmd);
        tx_byte(a[23:16]); tx_byte(a[15:8]); tx_byte(a[7:0]);
        tx_byte(n[15:8]);  tx_byte(n[7:0]);
    endtask

    task automatic expect_status(input [7:0] st, input string what);
        checks++;
        if (st !== ACK) begin
            errors++;
            $display("  FAIL %0s: status %02h (expected ACK)", what, st);
        end
    endtask

    // ---- 'I': one chunk of the firmware image, MSB byte of each word first ---
    task automatic uart_load_fw_chunk(input int first_word, input int nwords);
        logic [7:0] st;
        fork
            begin
                send_header(ICMD, 24'(FW_BASE + first_word), 16'(nwords * 4));
                for (int w = 0; w < nwords; w++) begin
                    tx_byte(fw_words[first_word + w][31:24]);
                    tx_byte(fw_words[first_word + w][23:16]);
                    tx_byte(fw_words[first_word + w][15:8]);
                    tx_byte(fw_words[first_word + w][7:0]);
                end
            end
            rx_byte(st);
        join
        expect_status(st, $sformatf("'I' @word %0d", first_word));
    endtask

    task automatic uart_load_firmware();
        int done_w, n;
        done_w = 0;
        while (done_w < n_fw_words) begin
            n = n_fw_words - done_w;
            if (n > `UART_CHUNK / 4) n = `UART_CHUNK / 4;
            uart_load_fw_chunk(done_w, n);
            done_w += n;
        end
        $display("  'I' loaded %0d firmware words (%0d bytes)",
                 n_fw_words, n_fw_words * 4);
    endtask

    // ---- 'W': one chunk of the operand image --------------------------------
    task automatic uart_write_chunk(input int start, input int n);
        logic [7:0] st;
        fork
            begin
                send_header(WCMD, 24'(start), 16'(n));
                for (int i = 0; i < n; i++) tx_byte(dram_in[start + i]);
            end
            rx_byte(st);
        join
        expect_status(st, $sformatf("'W' @%05h", start));
    endtask

    // ---- 'R': one chunk of the result image, compared as it arrives ---------
    task automatic uart_read_chunk(input int start, input int n);
        logic [7:0] b;
        fork
            send_header(RCMD, 24'(start), 16'(n));
            begin
                for (int i = 0; i < n; i++) begin
                    rx_byte(b);
                    checks++;
                    if (b !== dram_exp[start + i]) begin
                        errors++;
                        if (errors <= 16)
                            $display("  FAIL 'R' @%05h: got %02h, expected %02h",
                                     start + i, b, dram_exp[start + i]);
                    end
                end
            end
        join
    endtask

    // Walk a sparse byte image and hand each contiguous run to `op`, split at
    // UART_CHUNK. 0 = write the operands, 1 = read the results back.
    task automatic uart_walk_runs(input int op);
        int a, start, n, part, bytes, frames;
        a = 0; bytes = 0; frames = 0;
        while (a < SRAM_SZ) begin
            if ((op == 0) ? defined8(dram_in[a]) : defined8(dram_exp[a])) begin
                start = a; n = 0;
                while (a < SRAM_SZ &&
                       ((op == 0) ? defined8(dram_in[a]) : defined8(dram_exp[a]))) begin
                    a++; n++;
                end
                while (n > 0) begin
                    part = (n > `UART_CHUNK) ? `UART_CHUNK : n;
                    if (op == 0) uart_write_chunk(start, part);
                    else         uart_read_chunk (start, part);
                    start += part; n -= part; bytes += part; frames++;
                end
            end else a++;
        end
        $display("  '%0s' %0d bytes in %0d frames", (op == 0) ? "W" : "R",
                 bytes, frames);   // both literals are one byte wide
    endtask

    // ---- 'G': release the core ----------------------------------------------
    task automatic uart_go(input [23:0] pc);
        logic [7:0] st;
        fork
            begin
                tx_byte(GCMD);
                tx_byte(pc[23:16]); tx_byte(pc[15:8]); tx_byte(pc[7:0]);
            end
            rx_byte(st);
        join
        expect_status(st, "'G'");
    endtask

    // ---- 'T': the counter block ---------------------------------------------
    // Packed rather than an unpacked array of words: Icarus does not support
    // unpacked dimensions on subroutine ports. Word w is ctr_w(ctr, w).
    task automatic uart_read_timer(output [NPERF*32-1:0] ctr);
        logic [7:0] b;
        fork
            tx_byte(TCMD);
            begin
                ctr = '0;
                for (int i = 0; i < NPERF*4; i++) begin
                    rx_byte(b);
                    ctr = {ctr[NPERF*32-9:0], b};
                end
            end
        join
    endtask

    // =========================================================================
    // Loading / checking
    // =========================================================================
    task automatic load_vectors();
        for (int i = 0; i < FW_DEPTH; i++) fw_words[i] = 32'hxxxx_xxxx;
        for (int i = 0; i < SRAM_SZ; i++) begin
            dram_in[i]  = 8'hxx;
            dram_exp[i] = 8'hxx;
        end
        for (int i = 0; i < MAX_CMDS*5; i++) cmd_exp[i] = 32'hxxxx_xxxx;

        $readmemh(`FW_HEX, fw_words);
        $readmemh({`FW_VEC_DIR, "/fw_dram_in.hex"},  dram_in);
        $readmemh({`FW_VEC_DIR, "/fw_dram_exp.hex"}, dram_exp);
        $readmemh({`FW_VEC_DIR, "/fw_cmds.hex"},     cmd_exp);

        n_fw_words = 0;
        while (n_fw_words < FW_DEPTH && defined32(fw_words[n_fw_words])) n_fw_words++;
        if (n_fw_words == 0) begin
            $display("FW_UART: %s is empty or missing - build it first (make -C ../fw PROG=%s)",
                     `FW_HEX, `FW_NAME);
            $fatal(1);
        end

        n_cmd_exp = 0;
        while (n_cmd_exp < MAX_CMDS && cmd_exp[n_cmd_exp*5] !== 32'hffff_ffff &&
               cmd_exp[n_cmd_exp*5] !== 32'hxxxx_xxxx)
            n_cmd_exp++;
        if (n_cmd_exp == 0) begin
            $display("FW_UART: no vectors in %s - run fw_vectors.py first",
                     `FW_VEC_DIR);
            $fatal(1);
        end
    endtask

    // Every byte of DRAM, by backdoor. A byte the golden run wrote must match
    // it; every other byte must still hold what 'W' put there (or 0). This is
    // the stray-write sweep — see the file header on why it is not over UART.
    task automatic check_dram_backdoor();
        logic [7:0] want;
        int         bad;
        bad = 0;
        for (int a = 0; a < SRAM_SZ; a++) begin
            if (dram_exp[a] !== 8'hxx)     want = dram_exp[a];
            else if (dram_in[a] !== 8'hxx) want = dram_in[a];
            else                           want = 8'h00;
            checks++;
            if (sram_mem[a] !== want) begin
                bad++;
                errors++;
                if (bad <= 8)
                    $display("  FAIL DRAM[0x%05h] = 0x%02h, expected 0x%02h%s",
                             a, sram_mem[a], want,
                             (dram_exp[a] === 8'hxx) ? "  (untouched byte was written)"
                                                     : "");
            end
        end
        $display("  backdoor sweep: %0d of %0d DRAM bytes wrong", bad, SRAM_SZ);
    endtask

    task automatic check_cmds();
        checks++;
        if (n_cmd_got > MAX_CMDS || n_cmd_exp >= MAX_CMDS) begin
            errors++;
            $display("  FAIL trace does not fit MAX_CMDS=%0d (got %0d, expected %0d)",
                     MAX_CMDS, n_cmd_got, n_cmd_exp);
        end
        if (n_cmd_got !== n_cmd_exp) begin
            errors++;
            $display("  FAIL command count: RTL issued %0d, expected %0d",
                     n_cmd_got, n_cmd_exp);
        end
        for (int i = 0; i < n_cmd_exp && i < n_cmd_got; i++)
            for (int w = 0; w < 5; w++) begin
                checks++;
                if (cmd_got[i*5 + w] !== cmd_exp[i*5 + w]) begin
                    errors++;
                    $display("  FAIL cmd[%0d] word %0d: RTL %08h, expected %08h",
                             i, w, cmd_got[i*5 + w], cmd_exp[i*5 + w]);
                    $display("       RTL      unit=%0d %08h %08h %08h %08h",
                             cmd_got[i*5+0], cmd_got[i*5+1], cmd_got[i*5+2],
                             cmd_got[i*5+3], cmd_got[i*5+4]);
                    $display("       expected unit=%0d %08h %08h %08h %08h",
                             cmd_exp[i*5+0], cmd_exp[i*5+1], cmd_exp[i*5+2],
                             cmd_exp[i*5+3], cmd_exp[i*5+4]);
                end
            end
        $display("  command trace: %0d commands issued, %0d expected",
                 n_cmd_got, n_cmd_exp);
    endtask

    // The counter block, checked for the invariants that hold for any kernel —
    // this tests perf_counters.sv and the 'T' reply rather than this particular
    // program. The per-unit expectations are derived from the *expected command
    // trace*, so they follow whatever kernel the Makefile was given.
    task automatic check_counters(input logic [NPERF*32-1:0] ctr);
        bit expect_mxu, expect_vpu, expect_dma;
        int unsigned want;

        expect_mxu = 1'b0; expect_vpu = 1'b0; expect_dma = 1'b0;
        for (int i = 0; i < n_cmd_exp; i++) begin
            // unit 0/1/2 = MXU/VPU/DMA; the executing opcode is MXU_MM (0x02)
            // for the MXU and VPU_OP / DMA_MOVE (0x01) for the other two. A
            // GEOM command configures and retires without starting its unit.
            if (cmd_exp[i*5] == 0 && cmd_exp[i*5+1][7:0] == 8'h02) expect_mxu = 1'b1;
            if (cmd_exp[i*5] == 1 && cmd_exp[i*5+1][7:0] == 8'h01) expect_vpu = 1'b1;
            if (cmd_exp[i*5] == 2 && cmd_exp[i*5+1][7:0] == 8'h01) expect_dma = 1'b1;
        end

        $display("  counters: run=%0d mxu=%0d mload=%0d vpu=%0d (vmm=%0d) dma=%0d",
                 ctr_w(ctr, P_RUN), ctr_w(ctr, P_MXU), ctr_w(ctr, P_MLOAD),
                 ctr_w(ctr, P_VPU), ctr_w(ctr, P_VMM), ctr_w(ctr, P_DMA));
        $display("            idlec=%0d qfull=%0d ovlap=%0d",
                 ctr_w(ctr, P_IDLEC), ctr_w(ctr, P_QFULL), ctr_w(ctr, P_OVLAP));

        // The device's own measure of the run against the testbench's.
        want = busy_clocks();
        checks++;
        if (ctr_w(ctr, P_RUN) !== want) begin
            errors++;
            $display("  FAIL 'T' reported %0d run clocks, `busy` was high for %0d",
                     ctr_w(ctr, P_RUN), want);
        end

        // Structural: every counter is gated by the same run window, and two of
        // them are sub-states of another.
        for (int i = 0; i < NPERF; i++) begin
            checks++;
            if (ctr_w(ctr, i) > ctr_w(ctr, P_RUN)) begin
                errors++;
                $display("  FAIL counter %0d = %0d exceeds run length %0d",
                         i, ctr_w(ctr, i), ctr_w(ctr, P_RUN));
            end
        end
        checks++;
        if (ctr_w(ctr, P_MLOAD) > ctr_w(ctr, P_MXU)) begin
            errors++;
            $display("  FAIL mload=%0d exceeds mxu=%0d (must be a subset)",
                     ctr_w(ctr, P_MLOAD), ctr_w(ctr, P_MXU));
        end
        checks++;
        if (ctr_w(ctr, P_VMM) > ctr_w(ctr, P_VPU)) begin
            errors++;
            $display("  FAIL vmm=%0d exceeds vpu=%0d (must be a subset)",
                     ctr_w(ctr, P_VMM), ctr_w(ctr, P_VPU));
        end

        // Per-unit: nonzero exactly when the expected trace runs that unit.
        checks++;
        if (expect_mxu != (ctr_w(ctr, P_MXU) != 0)) begin
            errors++;
            $display("  FAIL mxu counter is %0d but the expected trace has %0d matmuls",
                     ctr_w(ctr, P_MXU), expect_mxu);
        end
        checks++;
        if (expect_vpu != (ctr_w(ctr, P_VPU) != 0)) begin
            errors++;
            $display("  FAIL vpu counter is %0d but the expected trace has %0d VPU ops",
                     ctr_w(ctr, P_VPU), expect_vpu);
        end
        checks++;
        if (expect_dma != (ctr_w(ctr, P_DMA) != 0)) begin
            errors++;
            $display("  FAIL dma counter is %0d but the expected trace has %0d transfers",
                     ctr_w(ctr, P_DMA), expect_dma);
        end
        // A matmul must load weights first, so mload is nonzero — and strictly
        // less than mxu — exactly when the array ran.
        // retired, mload is no longer a thing
        // if (expect_mxu) begin
        //     checks++;
        //     if (ctr_w(ctr, P_MLOAD) == 0 ||
        //         ctr_w(ctr, P_MLOAD) >= ctr_w(ctr, P_MXU)) begin
        //         errors++;
        //         $display("  FAIL mload=%0d is not a strict subset of mxu=%0d",
        //                  ctr_w(ctr, P_MLOAD), ctr_w(ctr, P_MXU));
        //     end
        // end
    endtask

    // `done` is level-held after a run, so a second 'G' would fall straight
    // through a bare `wait (done)`. Wait for the core to pick the run up first.
    task automatic wait_for_halt();
        int n;
        n = 0;
        while (!busy && n < 100000) begin @(negedge clk); n++; end
        checks++;
        if (!busy) begin
            errors++;
            $display("  FAIL core never started after 'G' (done=%0b)", done);
        end else begin
            do @(negedge clk); while (!done);
        end
        checks++;
        if (dut.cpu_trap) begin
            errors++;
            $display("  FAIL the firmware trapped (illegal instruction or ebreak)");
        end
    endtask

    // =========================================================================
    // One full pass: load, stage, run, read back, check.
    // =========================================================================
    task automatic run_pass(input string label);
        logic [NPERF*32-1:0] ctr;
        int unsigned t0;

        $display("---- %0s ----", label);
        n_cmd_got = 0;

        uart_load_firmware();
        uart_walk_runs(0);                  // 'W' operands, weights included

        t0 = cyc;
        uart_go(24'(FW_BASE));
        wait_for_halt();
        $display("  firmware signalled done, %0d clocks after 'G'", cyc - t0);

        uart_read_timer(ctr);
        check_counters(ctr);

        uart_walk_runs(1);                  // 'R' the results, compared as read
        check_dram_backdoor();
        check_cmds();

        $display("---- %0s: %0d checks, %0d errors so far ----",
                 label, checks, errors);
    endtask

    // =========================================================================
    // Stimulus
    // =========================================================================
    initial begin
        $display("==== firmware over UART: %s (%s), %0dx%0d array, CPB=%0d ====",
                 `FW_NAME, `FW_HEX, ROWS, COLS, CPB);

        load_vectors();
        // DRAM starts blank: everything the run reads must have arrived over the
        // wire, so a missing 'W' frame is a wrong answer and not a stale hit.
        for (int i = 0; i < SRAM_SZ; i++) sram_mem[i] = 8'h00;

        repeat (4) @(negedge clk);
        rst_n = 1'b1;
        repeat (4) @(negedge clk);
        last_wire_edge = $time;

        run_pass("pass 1");

        // A second load + run over the same link with no reset in between —
        // what two back-to-back run_fw_matmul.py invocations do on the board.
        // Not a formality: this is what caught tpu_top.sv clearing `cpu_run`
        // against the *previous* run's still-latched `cpu_done`, so the second
        // 'G' released the core for one cycle and put it straight back into
        // reset while every command ACK'd (docs/picorv32_migration.md §9.11).
        // Nothing that runs one program per reset can see that.
        if ($test$plusargs("RERUN")) begin
            repeat (100) @(posedge clk);
            run_pass("pass 2 (no reset in between)");
        end

        $display("==== done: %0d checks, %0d errors ====", checks, errors);
        if (errors == 0) $display("FW_UART: ALL TESTS PASSED");
        else             $display("FW_UART: %0d FAILURES", errors);
        $finish;
    end

    // ---- watchdogs -----------------------------------------------------------
    // Two, because "the link wedged" and "the core never halted" have very
    // different timescales and one bound cannot catch both: the adder computes
    // for 4.5 ms with both serial lines idle, so any link timeout loose enough
    // to survive that would never fire on a real stall.
    initial forever begin
        #100000;                                        // 0.1 ms
        if (busy) begin
            if ($time - t_busy_rise > `RUN_MAX_NS) begin
                $display("FW_UART: WATCHDOG - core busy for over %0d ns without halting",
                         `RUN_MAX_NS);
                $fatal(1);
            end
        end else if ($time - last_wire_edge > `LINK_IDLE_NS) begin
            $display("FW_UART: WATCHDOG - serial link idle for over %0d ns (wedged)",
                     `LINK_IDLE_NS);
            $fatal(1);
        end
    end

    // Off by default: the adder run is millions of clocks and its VCD is
    // enormous. `vvp fw_uart_tb.vvp +VCD`.
    initial if ($test$plusargs("VCD")) begin
        $dumpfile("fw_uart_tb.vcd");
        $dumpvars(0, fw_uart_tb);
    end

endmodule
